version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/agent"
      - "/site"
      - "/ui"
    schedule:
      interval: "weekly"
    groups:
      go-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      go-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
