//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentCapability.
const (
	AgentCapabilityDns                 AgentCapability = "dns"
	AgentCapabilityHttp                AgentCapability = "http"
	AgentCapabilityKubernetesDiscovery AgentCapability = "kubernetes-discovery"
	AgentCapabilityKubernetesWatch     AgentCapability = "kubernetes-watch"
	AgentCapabilityTcp                 AgentCapability = "tcp"
)

// Valid indicates whether the value is a known member of the AgentCapability enum.
func (e AgentCapability) Valid() bool {
	switch e {
	case AgentCapabilityDns:
		return true
	case AgentCapabilityHttp:
		return true
	case AgentCapabilityKubernetesDiscovery:
		return true
	case AgentCapabilityKubernetesWatch:
		return true
	case AgentCapabilityTcp:
		return true
	default:
		return false
	}
}

// Defines values for DNSProbeDefinitionKind.
const (
	DNSProbeDefinitionKindDns DNSProbeDefinitionKind = "dns"
)

// Valid indicates whether the value is a known member of the DNSProbeDefinitionKind enum.
func (e DNSProbeDefinitionKind) Valid() bool {
	switch e {
	case DNSProbeDefinitionKindDns:
		return true
	default:
		return false
	}
}

// Defines values for DNSProbeDefinitionRecordType.
const (
	A     DNSProbeDefinitionRecordType = "A"
	AAAA  DNSProbeDefinitionRecordType = "AAAA"
	CNAME DNSProbeDefinitionRecordType = "CNAME"
	MX    DNSProbeDefinitionRecordType = "MX"
	NS    DNSProbeDefinitionRecordType = "NS"
	SRV   DNSProbeDefinitionRecordType = "SRV"
	TXT   DNSProbeDefinitionRecordType = "TXT"
)

// Valid indicates whether the value is a known member of the DNSProbeDefinitionRecordType enum.
func (e DNSProbeDefinitionRecordType) Valid() bool {
	switch e {
	case A:
		return true
	case AAAA:
		return true
	case CNAME:
		return true
	case MX:
		return true
	case NS:
		return true
	case SRV:
		return true
	case TXT:
		return true
	default:
		return false
	}
}

// Defines values for HTTPProbeDefinitionKind.
const (
	HTTPProbeDefinitionKindHttp HTTPProbeDefinitionKind = "http"
)

// Valid indicates whether the value is a known member of the HTTPProbeDefinitionKind enum.
func (e HTTPProbeDefinitionKind) Valid() bool {
	switch e {
	case HTTPProbeDefinitionKindHttp:
		return true
	default:
		return false
	}
}

// Defines values for HTTPProbeDefinitionMethod.
const (
	DELETE  HTTPProbeDefinitionMethod = "DELETE"
	GET     HTTPProbeDefinitionMethod = "GET"
	HEAD    HTTPProbeDefinitionMethod = "HEAD"
	OPTIONS HTTPProbeDefinitionMethod = "OPTIONS"
	PATCH   HTTPProbeDefinitionMethod = "PATCH"
	POST    HTTPProbeDefinitionMethod = "POST"
	PUT     HTTPProbeDefinitionMethod = "PUT"
)

// Valid indicates whether the value is a known member of the HTTPProbeDefinitionMethod enum.
func (e HTTPProbeDefinitionMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case HEAD:
		return true
	case OPTIONS:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for HealthState.
const (
	Degraded HealthState = "degraded"
	Down     HealthState = "down"
	Pending  HealthState = "pending"
	Unknown  HealthState = "unknown"
	Up       HealthState = "up"
)

// Valid indicates whether the value is a known member of the HealthState enum.
func (e HealthState) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Down:
		return true
	case Pending:
		return true
	case Unknown:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for IncidentSeverity.
const (
	Critical IncidentSeverity = "critical"
)

// Valid indicates whether the value is a known member of the IncidentSeverity enum.
func (e IncidentSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	default:
		return false
	}
}

// Defines values for IncidentState.
const (
	Open     IncidentState = "open"
	Resolved IncidentState = "resolved"
)

// Valid indicates whether the value is a known member of the IncidentState enum.
func (e IncidentState) Valid() bool {
	switch e {
	case Open:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for MonitorKind.
const (
	MonitorKindDns  MonitorKind = "dns"
	MonitorKindHttp MonitorKind = "http"
	MonitorKindTcp  MonitorKind = "tcp"
)

// Valid indicates whether the value is a known member of the MonitorKind enum.
func (e MonitorKind) Valid() bool {
	switch e {
	case MonitorKindDns:
		return true
	case MonitorKindHttp:
		return true
	case MonitorKindTcp:
		return true
	default:
		return false
	}
}

// Defines values for ProbeResultAcknowledgementStatus.
const (
	Accepted  ProbeResultAcknowledgementStatus = "accepted"
	Duplicate ProbeResultAcknowledgementStatus = "duplicate"
)

// Valid indicates whether the value is a known member of the ProbeResultAcknowledgementStatus enum.
func (e ProbeResultAcknowledgementStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Duplicate:
		return true
	default:
		return false
	}
}

// Defines values for ProbeResultInputErrorCode.
const (
	BodyMismatch      ProbeResultInputErrorCode = "body_mismatch"
	ConnectError      ProbeResultInputErrorCode = "connect_error"
	DnsError          ProbeResultInputErrorCode = "dns_error"
	DnsMismatch       ProbeResultInputErrorCode = "dns_mismatch"
	Empty             ProbeResultInputErrorCode = ""
	ProtocolError     ProbeResultInputErrorCode = "protocol_error"
	ResponseTooLarge  ProbeResultInputErrorCode = "response_too_large"
	StatusMismatch    ProbeResultInputErrorCode = "status_mismatch"
	TargetDenied      ProbeResultInputErrorCode = "target_denied"
	TcpExpectMismatch ProbeResultInputErrorCode = "tcp_expect_mismatch"
	Timeout           ProbeResultInputErrorCode = "timeout"
	TlsError          ProbeResultInputErrorCode = "tls_error"
	TlsExpiring       ProbeResultInputErrorCode = "tls_expiring"
)

// Valid indicates whether the value is a known member of the ProbeResultInputErrorCode enum.
func (e ProbeResultInputErrorCode) Valid() bool {
	switch e {
	case BodyMismatch:
		return true
	case ConnectError:
		return true
	case DnsError:
		return true
	case DnsMismatch:
		return true
	case Empty:
		return true
	case ProtocolError:
		return true
	case ResponseTooLarge:
		return true
	case StatusMismatch:
		return true
	case TargetDenied:
		return true
	case TcpExpectMismatch:
		return true
	case Timeout:
		return true
	case TlsError:
		return true
	case TlsExpiring:
		return true
	default:
		return false
	}
}

// Defines values for ProbeResultInputOutcome.
const (
	Failed ProbeResultInputOutcome = "failed"
	Passed ProbeResultInputOutcome = "passed"
)

// Valid indicates whether the value is a known member of the ProbeResultInputOutcome enum.
func (e ProbeResultInputOutcome) Valid() bool {
	switch e {
	case Failed:
		return true
	case Passed:
		return true
	default:
		return false
	}
}

// Defines values for TCPProbeDefinitionKind.
const (
	TCPProbeDefinitionKindTcp TCPProbeDefinitionKind = "tcp"
)

// Valid indicates whether the value is a known member of the TCPProbeDefinitionKind enum.
func (e TCPProbeDefinitionKind) Valid() bool {
	switch e {
	case TCPProbeDefinitionKindTcp:
		return true
	default:
		return false
	}
}

// AgentCapability defines model for AgentCapability.
type AgentCapability string

// AgentEnrollmentToken defines model for AgentEnrollmentToken.
type AgentEnrollmentToken struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// AgentHeartbeat defines model for AgentHeartbeat.
type AgentHeartbeat struct {
	Capabilities         []AgentCapability `json:"capabilities"`
	CredentialGeneration int64             `json:"credentialGeneration"`
	Version              string            `json:"version"`
}

// CreateAgentEnrollmentTokenRequest defines model for CreateAgentEnrollmentTokenRequest.
type CreateAgentEnrollmentTokenRequest struct {
	ExpiresInSeconds int32              `json:"expiresInSeconds"`
	LocationId       openapi_types.UUID `json:"locationId"`
}

// CreateLocationRequest defines model for CreateLocationRequest.
type CreateLocationRequest struct {
	Name string `json:"name"`
}

// CreateMonitorRequest defines model for CreateMonitorRequest.
type CreateMonitorRequest struct {
	FailureThreshold  int32              `json:"failureThreshold"`
	IntervalSeconds   int32              `json:"intervalSeconds"`
	LocationId        openapi_types.UUID `json:"locationId"`
	Name              string             `json:"name"`
	Probe             ProbeDefinition    `json:"probe"`
	RecoveryThreshold int32              `json:"recoveryThreshold"`
	RequiredLocation  bool               `json:"requiredLocation"`
	TimeoutMillis     int32              `json:"timeoutMillis"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// DNSProbeDefinition defines model for DNSProbeDefinition.
type DNSProbeDefinition struct {
	ExpectedValues []string                     `json:"expectedValues"`
	Kind           DNSProbeDefinitionKind       `json:"kind"`
	Name           string                       `json:"name"`
	RecordType     DNSProbeDefinitionRecordType `json:"recordType"`
	Resolver       string                       `json:"resolver"`
}

// DNSProbeDefinitionKind defines model for DNSProbeDefinition.Kind.
type DNSProbeDefinitionKind string

// DNSProbeDefinitionRecordType defines model for DNSProbeDefinition.RecordType.
type DNSProbeDefinitionRecordType string

// EnrollAgentRequest defines model for EnrollAgentRequest.
type EnrollAgentRequest struct {
	Capabilities []AgentCapability `json:"capabilities"`
	Name         string            `json:"name"`
	Token        *string           `json:"token,omitempty"`
}

// EnrolledAgent defines model for EnrolledAgent.
type EnrolledAgent struct {
	AgentId              openapi_types.UUID `json:"agentId"`
	Credential           string             `json:"credential"`
	CredentialGeneration int64              `json:"credentialGeneration"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// HTTPProbeDefinition defines model for HTTPProbeDefinition.
type HTTPProbeDefinition struct {
	Body                       []byte                    `json:"body"`
	BodyContains               []string                  `json:"bodyContains"`
	BodyDoesNotContain         []string                  `json:"bodyDoesNotContain"`
	ExpectedStatus             []StatusRange             `json:"expectedStatus"`
	FollowRedirects            bool                      `json:"followRedirects"`
	Headers                    map[string]string         `json:"headers"`
	Kind                       HTTPProbeDefinitionKind   `json:"kind"`
	Method                     HTTPProbeDefinitionMethod `json:"method"`
	TlsMinimumRemainingSeconds *int64                    `json:"tlsMinimumRemainingSeconds,omitempty"`
	Url                        string                    `json:"url"`
}

// HTTPProbeDefinitionKind defines model for HTTPProbeDefinition.Kind.
type HTTPProbeDefinitionKind string

// HTTPProbeDefinitionMethod defines model for HTTPProbeDefinition.Method.
type HTTPProbeDefinitionMethod string

// HealthState defines model for HealthState.
type HealthState string

// Incident defines model for Incident.
type Incident struct {
	Id               openapi_types.UUID `json:"id"`
	LastTransitionAt time.Time          `json:"lastTransitionAt"`
	MonitorId        openapi_types.UUID `json:"monitorId"`
	OpenedAt         time.Time          `json:"openedAt"`
	Severity         IncidentSeverity   `json:"severity"`
	State            IncidentState      `json:"state"`
}

// IncidentSeverity defines model for Incident.Severity.
type IncidentSeverity string

// IncidentState defines model for Incident.State.
type IncidentState string

// LeaseWorkRequest defines model for LeaseWorkRequest.
type LeaseWorkRequest struct {
	Capabilities []AgentCapability `json:"capabilities"`
	WaitSeconds  int32             `json:"waitSeconds"`
}

// Location defines model for Location.
type Location struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// LocationHealth defines model for LocationHealth.
type LocationHealth struct {
	ConsecutiveFailures  int32              `json:"consecutiveFailures"`
	ConsecutiveSuccesses int32              `json:"consecutiveSuccesses"`
	LastObservedAt       time.Time          `json:"lastObservedAt"`
	LocationId           openapi_types.UUID `json:"locationId"`
	State                HealthState        `json:"state"`
}

// Monitor defines model for Monitor.
type Monitor struct {
	CreatedAt         time.Time          `json:"createdAt"`
	FailureThreshold  int32              `json:"failureThreshold"`
	Id                openapi_types.UUID `json:"id"`
	IntervalSeconds   int32              `json:"intervalSeconds"`
	Kind              MonitorKind        `json:"kind"`
	LocationId        openapi_types.UUID `json:"locationId"`
	Name              string             `json:"name"`
	Probe             ProbeDefinition    `json:"probe"`
	RecoveryThreshold int32              `json:"recoveryThreshold"`
	RequiredLocation  bool               `json:"requiredLocation"`
	TimeoutMillis     int32              `json:"timeoutMillis"`
	UpdatedAt         time.Time          `json:"updatedAt"`
}

// MonitorKind defines model for Monitor.Kind.
type MonitorKind string

// MonitorHealth defines model for MonitorHealth.
type MonitorHealth struct {
	LastTransitionAt time.Time          `json:"lastTransitionAt"`
	Locations        []LocationHealth   `json:"locations"`
	MonitorId        openapi_types.UUID `json:"monitorId"`
	State            HealthState        `json:"state"`
}

// ProbeDefinition defines model for ProbeDefinition.
type ProbeDefinition struct {
	union json.RawMessage
}

// ProbeResultAcknowledgement defines model for ProbeResultAcknowledgement.
type ProbeResultAcknowledgement struct {
	ResultId openapi_types.UUID               `json:"resultId"`
	Status   ProbeResultAcknowledgementStatus `json:"status"`
}

// ProbeResultAcknowledgementStatus defines model for ProbeResultAcknowledgement.Status.
type ProbeResultAcknowledgementStatus string

// ProbeResultBatch defines model for ProbeResultBatch.
type ProbeResultBatch struct {
	Results []ProbeResultInput `json:"results"`
}

// ProbeResultBatchAcknowledgement defines model for ProbeResultBatchAcknowledgement.
type ProbeResultBatchAcknowledgement struct {
	Acknowledgements []ProbeResultAcknowledgement `json:"acknowledgements"`
}

// ProbeResultInput defines model for ProbeResultInput.
type ProbeResultInput struct {
	BodyAssertionPassed bool                      `json:"bodyAssertionPassed"`
	DiagnosticSample    string                    `json:"diagnosticSample"`
	ErrorCode           ProbeResultInputErrorCode `json:"errorCode"`
	FinishedAt          time.Time                 `json:"finishedAt"`
	LatencyMillis       int64                     `json:"latencyMillis"`
	LeaseToken          string                    `json:"leaseToken"`
	ObservedStatus      int32                     `json:"observedStatus"`
	ObservedValues      *[]string                 `json:"observedValues,omitempty"`
	Outcome             ProbeResultInputOutcome   `json:"outcome"`
	ProtocolTimings     *ProtocolTimings          `json:"protocolTimings,omitempty"`
	ResultId            openapi_types.UUID        `json:"resultId"`
	RunId               openapi_types.UUID        `json:"runId"`
	StartedAt           time.Time                 `json:"startedAt"`
	TlsNotAfter         *time.Time                `json:"tlsNotAfter,omitempty"`
}

// ProbeResultInputErrorCode defines model for ProbeResultInput.ErrorCode.
type ProbeResultInputErrorCode string

// ProbeResultInputOutcome defines model for ProbeResultInput.Outcome.
type ProbeResultInputOutcome string

// ProbeWork defines model for ProbeWork.
type ProbeWork struct {
	LeaseToken    string             `json:"leaseToken"`
	MonitorId     openapi_types.UUID `json:"monitorId"`
	Probe         ProbeDefinition    `json:"probe"`
	RunId         openapi_types.UUID `json:"runId"`
	ScheduledFor  time.Time          `json:"scheduledFor"`
	TimeoutMillis int32              `json:"timeoutMillis"`
}

// Problem defines model for Problem.
type Problem struct {
	Code          string        `json:"code"`
	CorrelationId string        `json:"correlationId"`
	Detail        *string       `json:"detail,omitempty"`
	FieldErrors   *[]FieldError `json:"fieldErrors,omitempty"`
	Status        int32         `json:"status"`
	Title         string        `json:"title"`
	Type          string        `json:"type"`
}

// ProtocolTimings defines model for ProtocolTimings.
type ProtocolTimings struct {
	ConnectMillis   *int64 `json:"connectMillis,omitempty"`
	DnsMillis       *int64 `json:"dnsMillis,omitempty"`
	FirstByteMillis *int64 `json:"firstByteMillis,omitempty"`
	TlsMillis       *int64 `json:"tlsMillis,omitempty"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// StatusRange defines model for StatusRange.
type StatusRange struct {
	Maximum int32 `json:"maximum"`
	Minimum int32 `json:"minimum"`
}

// TCPProbeDefinition defines model for TCPProbeDefinition.
type TCPProbeDefinition struct {
	Expect                     []byte                 `json:"expect"`
	Host                       string                 `json:"host"`
	Kind                       TCPProbeDefinitionKind `json:"kind"`
	Port                       int32                  `json:"port"`
	Send                       []byte                 `json:"send"`
	TlsMinimumRemainingSeconds *int64                 `json:"tlsMinimumRemainingSeconds,omitempty"`
}

// TCPProbeDefinitionKind defines model for TCPProbeDefinition.Kind.
type TCPProbeDefinitionKind string

// MonitorID defines model for MonitorID.
type MonitorID = openapi_types.UUID

// CreateAgentEnrollmentTokenJSONRequestBody defines body for CreateAgentEnrollmentToken for application/json ContentType.
type CreateAgentEnrollmentTokenJSONRequestBody = CreateAgentEnrollmentTokenRequest

// EnrollAgentJSONRequestBody defines body for EnrollAgent for application/json ContentType.
type EnrollAgentJSONRequestBody = EnrollAgentRequest

// HeartbeatAgentJSONRequestBody defines body for HeartbeatAgent for application/json ContentType.
type HeartbeatAgentJSONRequestBody = AgentHeartbeat

// UploadProbeResultsJSONRequestBody defines body for UploadProbeResults for application/json ContentType.
type UploadProbeResultsJSONRequestBody = ProbeResultBatch

// LeaseAgentWorkJSONRequestBody defines body for LeaseAgentWork for application/json ContentType.
type LeaseAgentWorkJSONRequestBody = LeaseWorkRequest

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = CreateLocationRequest

// CreateMonitorJSONRequestBody defines body for CreateMonitor for application/json ContentType.
type CreateMonitorJSONRequestBody = CreateMonitorRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// AsHTTPProbeDefinition returns the union data inside the ProbeDefinition as a HTTPProbeDefinition
func (t ProbeDefinition) AsHTTPProbeDefinition() (HTTPProbeDefinition, error) {
	var body HTTPProbeDefinition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHTTPProbeDefinition overwrites any union data inside the ProbeDefinition as the provided HTTPProbeDefinition
func (t *ProbeDefinition) FromHTTPProbeDefinition(v HTTPProbeDefinition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"http"}`))
	t.union = b
	return err
}

// MergeHTTPProbeDefinition performs a merge with any union data inside the ProbeDefinition, using the provided HTTPProbeDefinition
func (t *ProbeDefinition) MergeHTTPProbeDefinition(v HTTPProbeDefinition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"http"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTCPProbeDefinition returns the union data inside the ProbeDefinition as a TCPProbeDefinition
func (t ProbeDefinition) AsTCPProbeDefinition() (TCPProbeDefinition, error) {
	var body TCPProbeDefinition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTCPProbeDefinition overwrites any union data inside the ProbeDefinition as the provided TCPProbeDefinition
func (t *ProbeDefinition) FromTCPProbeDefinition(v TCPProbeDefinition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"tcp"}`))
	t.union = b
	return err
}

// MergeTCPProbeDefinition performs a merge with any union data inside the ProbeDefinition, using the provided TCPProbeDefinition
func (t *ProbeDefinition) MergeTCPProbeDefinition(v TCPProbeDefinition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"tcp"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDNSProbeDefinition returns the union data inside the ProbeDefinition as a DNSProbeDefinition
func (t ProbeDefinition) AsDNSProbeDefinition() (DNSProbeDefinition, error) {
	var body DNSProbeDefinition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDNSProbeDefinition overwrites any union data inside the ProbeDefinition as the provided DNSProbeDefinition
func (t *ProbeDefinition) FromDNSProbeDefinition(v DNSProbeDefinition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"dns"}`))
	t.union = b
	return err
}

// MergeDNSProbeDefinition performs a merge with any union data inside the ProbeDefinition, using the provided DNSProbeDefinition
func (t *ProbeDefinition) MergeDNSProbeDefinition(v DNSProbeDefinition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"dns"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ProbeDefinition) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ProbeDefinition) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "dns":
		return t.AsDNSProbeDefinition()
	case "http":
		return t.AsHTTPProbeDefinition()
	case "tcp":
		return t.AsTCPProbeDefinition()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ProbeDefinition) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ProbeDefinition) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/agent-enrollment-tokens)
	CreateAgentEnrollmentToken(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent-enrollments)
	EnrollAgent(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent/heartbeat)
	HeartbeatAgent(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent/results:batch)
	UploadProbeResults(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent/work:lease)
	LeaseAgentWork(w http.ResponseWriter, r *http.Request)

	// (POST /v1/locations)
	CreateLocation(w http.ResponseWriter, r *http.Request)

	// (POST /v1/monitors)
	CreateMonitor(w http.ResponseWriter, r *http.Request)

	// (GET /v1/monitors/{monitorId})
	GetMonitor(w http.ResponseWriter, r *http.Request, monitorId MonitorID)

	// (GET /v1/monitors/{monitorId}/active-incident)
	GetActiveMonitorIncident(w http.ResponseWriter, r *http.Request, monitorId MonitorID)

	// (GET /v1/monitors/{monitorId}/health)
	GetMonitorHealth(w http.ResponseWriter, r *http.Request, monitorId MonitorID)

	// (POST /v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAgentEnrollmentToken operation middleware
func (siw *ServerInterfaceWrapper) CreateAgentEnrollmentToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgentEnrollmentToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrollAgent operation middleware
func (siw *ServerInterfaceWrapper) EnrollAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrollAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeartbeatAgent operation middleware
func (siw *ServerInterfaceWrapper) HeartbeatAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeartbeatAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadProbeResults operation middleware
func (siw *ServerInterfaceWrapper) UploadProbeResults(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadProbeResults(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeaseAgentWork operation middleware
func (siw *ServerInterfaceWrapper) LeaseAgentWork(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeaseAgentWork(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLocation operation middleware
func (siw *ServerInterfaceWrapper) CreateLocation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLocation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMonitor operation middleware
func (siw *ServerInterfaceWrapper) CreateMonitor(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMonitor(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonitor operation middleware
func (siw *ServerInterfaceWrapper) GetMonitor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "monitorId" -------------
	var monitorId MonitorID

	err = runtime.BindStyledParameterWithOptions("simple", "monitorId", r.PathValue("monitorId"), &monitorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "monitorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonitor(w, r, monitorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActiveMonitorIncident operation middleware
func (siw *ServerInterfaceWrapper) GetActiveMonitorIncident(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "monitorId" -------------
	var monitorId MonitorID

	err = runtime.BindStyledParameterWithOptions("simple", "monitorId", r.PathValue("monitorId"), &monitorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "monitorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActiveMonitorIncident(w, r, monitorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonitorHealth operation middleware
func (siw *ServerInterfaceWrapper) GetMonitorHealth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "monitorId" -------------
	var monitorId MonitorID

	err = runtime.BindStyledParameterWithOptions("simple", "monitorId", r.PathValue("monitorId"), &monitorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "monitorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonitorHealth(w, r, monitorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/locations", wrapper.CreateLocation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/monitors", wrapper.CreateMonitor)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/monitors/{monitorId}", wrapper.GetMonitor)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent-enrollment-tokens", wrapper.CreateAgentEnrollmentToken)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent-enrollments", wrapper.EnrollAgent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent/heartbeat", wrapper.HeartbeatAgent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent/work:lease", wrapper.LeaseAgentWork)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent/results:batch", wrapper.UploadProbeResults)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/monitors/{monitorId}/health", wrapper.GetMonitorHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/monitors/{monitorId}/active-incident", wrapper.GetActiveMonitorIncident)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type CreateAgentEnrollmentTokenRequestObject struct {
	Body *CreateAgentEnrollmentTokenJSONRequestBody
}

type CreateAgentEnrollmentTokenResponseObject interface {
	VisitCreateAgentEnrollmentTokenResponse(w http.ResponseWriter) error
}

type CreateAgentEnrollmentToken201JSONResponse AgentEnrollmentToken

func (response CreateAgentEnrollmentToken201JSONResponse) VisitCreateAgentEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentEnrollmentTokendefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateAgentEnrollmentTokendefaultApplicationProblemPlusJSONResponse) VisitCreateAgentEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollAgentRequestObject struct {
	Body *EnrollAgentJSONRequestBody
}

type EnrollAgentResponseObject interface {
	VisitEnrollAgentResponse(w http.ResponseWriter) error
}

type EnrollAgent201JSONResponse EnrolledAgent

func (response EnrollAgent201JSONResponse) VisitEnrollAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollAgentdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response EnrollAgentdefaultApplicationProblemPlusJSONResponse) VisitEnrollAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatAgentRequestObject struct {
	Body *HeartbeatAgentJSONRequestBody
}

type HeartbeatAgentResponseObject interface {
	VisitHeartbeatAgentResponse(w http.ResponseWriter) error
}

type HeartbeatAgent204Response struct {
}

func (response HeartbeatAgent204Response) VisitHeartbeatAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type HeartbeatAgentdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response HeartbeatAgentdefaultApplicationProblemPlusJSONResponse) VisitHeartbeatAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UploadProbeResultsRequestObject struct {
	Body *UploadProbeResultsJSONRequestBody
}

type UploadProbeResultsResponseObject interface {
	VisitUploadProbeResultsResponse(w http.ResponseWriter) error
}

type UploadProbeResults200JSONResponse ProbeResultBatchAcknowledgement

func (response UploadProbeResults200JSONResponse) VisitUploadProbeResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UploadProbeResultsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UploadProbeResultsdefaultApplicationProblemPlusJSONResponse) VisitUploadProbeResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type LeaseAgentWorkRequestObject struct {
	Body *LeaseAgentWorkJSONRequestBody
}

type LeaseAgentWorkResponseObject interface {
	VisitLeaseAgentWorkResponse(w http.ResponseWriter) error
}

type LeaseAgentWork200JSONResponse ProbeWork

func (response LeaseAgentWork200JSONResponse) VisitLeaseAgentWorkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LeaseAgentWork204Response struct {
}

func (response LeaseAgentWork204Response) VisitLeaseAgentWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LeaseAgentWorkdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response LeaseAgentWorkdefaultApplicationProblemPlusJSONResponse) VisitLeaseAgentWorkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocationRequestObject struct {
	Body *CreateLocationJSONRequestBody
}

type CreateLocationResponseObject interface {
	VisitCreateLocationResponse(w http.ResponseWriter) error
}

type CreateLocation201JSONResponse Location

func (response CreateLocation201JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateLocationdefaultApplicationProblemPlusJSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMonitorRequestObject struct {
	Body *CreateMonitorJSONRequestBody
}

type CreateMonitorResponseObject interface {
	VisitCreateMonitorResponse(w http.ResponseWriter) error
}

type CreateMonitor201JSONResponse Monitor

func (response CreateMonitor201JSONResponse) VisitCreateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMonitordefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateMonitordefaultApplicationProblemPlusJSONResponse) VisitCreateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitorRequestObject struct {
	MonitorId MonitorID `json:"monitorId"`
}

type GetMonitorResponseObject interface {
	VisitGetMonitorResponse(w http.ResponseWriter) error
}

type GetMonitor200JSONResponse Monitor

func (response GetMonitor200JSONResponse) VisitGetMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitordefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMonitordefaultApplicationProblemPlusJSONResponse) VisitGetMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetActiveMonitorIncidentRequestObject struct {
	MonitorId MonitorID `json:"monitorId"`
}

type GetActiveMonitorIncidentResponseObject interface {
	VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error
}

type GetActiveMonitorIncident200JSONResponse Incident

func (response GetActiveMonitorIncident200JSONResponse) VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetActiveMonitorIncident204Response struct {
}

func (response GetActiveMonitorIncident204Response) VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetActiveMonitorIncidentdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetActiveMonitorIncidentdefaultApplicationProblemPlusJSONResponse) VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitorHealthRequestObject struct {
	MonitorId MonitorID `json:"monitorId"`
}

type GetMonitorHealthResponseObject interface {
	VisitGetMonitorHealthResponse(w http.ResponseWriter) error
}

type GetMonitorHealth200JSONResponse MonitorHealth

func (response GetMonitorHealth200JSONResponse) VisitGetMonitorHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitorHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMonitorHealthdefaultApplicationProblemPlusJSONResponse) VisitGetMonitorHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse Session

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessiondefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateSessiondefaultApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /v1/agent-enrollment-tokens)
	CreateAgentEnrollmentToken(ctx context.Context, request CreateAgentEnrollmentTokenRequestObject) (CreateAgentEnrollmentTokenResponseObject, error)

	// (POST /v1/agent-enrollments)
	EnrollAgent(ctx context.Context, request EnrollAgentRequestObject) (EnrollAgentResponseObject, error)

	// (POST /v1/agent/heartbeat)
	HeartbeatAgent(ctx context.Context, request HeartbeatAgentRequestObject) (HeartbeatAgentResponseObject, error)

	// (POST /v1/agent/results:batch)
	UploadProbeResults(ctx context.Context, request UploadProbeResultsRequestObject) (UploadProbeResultsResponseObject, error)

	// (POST /v1/agent/work:lease)
	LeaseAgentWork(ctx context.Context, request LeaseAgentWorkRequestObject) (LeaseAgentWorkResponseObject, error)

	// (POST /v1/locations)
	CreateLocation(ctx context.Context, request CreateLocationRequestObject) (CreateLocationResponseObject, error)

	// (POST /v1/monitors)
	CreateMonitor(ctx context.Context, request CreateMonitorRequestObject) (CreateMonitorResponseObject, error)

	// (GET /v1/monitors/{monitorId})
	GetMonitor(ctx context.Context, request GetMonitorRequestObject) (GetMonitorResponseObject, error)

	// (GET /v1/monitors/{monitorId}/active-incident)
	GetActiveMonitorIncident(ctx context.Context, request GetActiveMonitorIncidentRequestObject) (GetActiveMonitorIncidentResponseObject, error)

	// (GET /v1/monitors/{monitorId}/health)
	GetMonitorHealth(ctx context.Context, request GetMonitorHealthRequestObject) (GetMonitorHealthResponseObject, error)

	// (POST /v1/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAgentEnrollmentToken operation middleware
func (sh *strictHandler) CreateAgentEnrollmentToken(w http.ResponseWriter, r *http.Request) {
	var request CreateAgentEnrollmentTokenRequestObject

	var body CreateAgentEnrollmentTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAgentEnrollmentToken(ctx, request.(CreateAgentEnrollmentTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAgentEnrollmentToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAgentEnrollmentTokenResponseObject); ok {
		if err := validResponse.VisitCreateAgentEnrollmentTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnrollAgent operation middleware
func (sh *strictHandler) EnrollAgent(w http.ResponseWriter, r *http.Request) {
	var request EnrollAgentRequestObject

	var body EnrollAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnrollAgent(ctx, request.(EnrollAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrollAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnrollAgentResponseObject); ok {
		if err := validResponse.VisitEnrollAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeartbeatAgent operation middleware
func (sh *strictHandler) HeartbeatAgent(w http.ResponseWriter, r *http.Request) {
	var request HeartbeatAgentRequestObject

	var body HeartbeatAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeartbeatAgent(ctx, request.(HeartbeatAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeartbeatAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeartbeatAgentResponseObject); ok {
		if err := validResponse.VisitHeartbeatAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadProbeResults operation middleware
func (sh *strictHandler) UploadProbeResults(w http.ResponseWriter, r *http.Request) {
	var request UploadProbeResultsRequestObject

	var body UploadProbeResultsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadProbeResults(ctx, request.(UploadProbeResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadProbeResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadProbeResultsResponseObject); ok {
		if err := validResponse.VisitUploadProbeResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LeaseAgentWork operation middleware
func (sh *strictHandler) LeaseAgentWork(w http.ResponseWriter, r *http.Request) {
	var request LeaseAgentWorkRequestObject

	var body LeaseAgentWorkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LeaseAgentWork(ctx, request.(LeaseAgentWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaseAgentWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LeaseAgentWorkResponseObject); ok {
		if err := validResponse.VisitLeaseAgentWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateLocation operation middleware
func (sh *strictHandler) CreateLocation(w http.ResponseWriter, r *http.Request) {
	var request CreateLocationRequestObject

	var body CreateLocationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateLocation(ctx, request.(CreateLocationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateLocation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateLocationResponseObject); ok {
		if err := validResponse.VisitCreateLocationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMonitor operation middleware
func (sh *strictHandler) CreateMonitor(w http.ResponseWriter, r *http.Request) {
	var request CreateMonitorRequestObject

	var body CreateMonitorJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMonitor(ctx, request.(CreateMonitorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMonitor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMonitorResponseObject); ok {
		if err := validResponse.VisitCreateMonitorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMonitor operation middleware
func (sh *strictHandler) GetMonitor(w http.ResponseWriter, r *http.Request, monitorId MonitorID) {
	var request GetMonitorRequestObject

	request.MonitorId = monitorId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitor(ctx, request.(GetMonitorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMonitorResponseObject); ok {
		if err := validResponse.VisitGetMonitorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetActiveMonitorIncident operation middleware
func (sh *strictHandler) GetActiveMonitorIncident(w http.ResponseWriter, r *http.Request, monitorId MonitorID) {
	var request GetActiveMonitorIncidentRequestObject

	request.MonitorId = monitorId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetActiveMonitorIncident(ctx, request.(GetActiveMonitorIncidentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetActiveMonitorIncident")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetActiveMonitorIncidentResponseObject); ok {
		if err := validResponse.VisitGetActiveMonitorIncidentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMonitorHealth operation middleware
func (sh *strictHandler) GetMonitorHealth(w http.ResponseWriter, r *http.Request, monitorId MonitorID) {
	var request GetMonitorHealthRequestObject

	request.MonitorId = monitorId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitorHealth(ctx, request.(GetMonitorHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitorHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMonitorHealthResponseObject); ok {
		if err := validResponse.VisitGetMonitorHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftbb9s6Ev4rBnffVqkvueAcv7lJehqgTYLE5wIUQUCLY5uNRKoklTQo/N8XJCWZkilLcuJ0C+xLG0sk",
	"Z+abK4fUDxTyOOEMmJJo/AMlWOAYFAjz6zNnVHFxcaZ/UIbGKMFqiQLEcAxojOLsPUEBEvAtpQIIGiuR",
	"QoBkuIQY64lzLmKs0BilKdUj1XOiJ0slKFug1WqlJ8uEMwmG6rXgswhi/WfImQKm9J84SSIaYkU56yd2",
	"xH++Ss70uzWtfwuYozH6V38tVt++lf18XUORgAwFTfRyaJyT7BFQmEYS6RHZNL3qZAFMneIEz2hE1bN+",
	"BCyN0fgLWiqVaJlC/S9hEgXoIZ2BYKBAHhAqQ/4I4rn8+AmrcInuNqAILKVzJngUxcDUlD+AkRATQjWv",
	"OLoWPAGhqMZqjiMJAUqcRz8QfE+oADlRJewJVnCgaAzIQ1XlZGLKPgFbqCUaH442NeVq+Us2K3AIriXi",
	"s68QqkKij4CFmgFWHWUJc8yz31RBLJv0XNXWKtByXdipw4JFLATWekkZ/ZZC9lrb7ipAoQACTFEc/QEM",
	"BLZm4sBJmTo5QmZhGmtLWK9LmYIFCE32EYTMZsb4e47syVHgAj1swjlfpYatoIySTwenArACn23dwLcU",
	"pNrNxC7YLYScEVmF5nCkocHfLTS/nRwNBg5UJwMfVhG3zn1B2sSMMkLO3GCTuXpEPmXzdkPBBsGSaoej",
	"QTfdmjXqGcwC8G78zTGNUgHTpQC55BHZrqVhSUdec9Z/ikcc7aT14xcrPfAhPho0IW5gmUGb7ABnMKfM",
	"4IuMomzwfj0Ec9XnhqcXzEbNOI8AG7o6TPNUfaZRRBtQHo4GgzLZgce7fEa3qc4q4WDTgnyYBGX32xAx",
	"x7/eym9Byp29EGJMoxJI9klQspLjI59dYCmfuCBVJx6MyhH6t+rcAD0JquCKRc9ZyqggnLNQUPAJf3Z5",
	"WzW6zmEYQgXkLxyllfzoiHM0+P2k0UVi/D3LgKNBJUOuAvRAGXGLHl3n3LX0z+PDRuLapgSZmsdrIhMU",
	"oMlkov87vZx8PkcB+vwPCtDlLQrQ9J8pCtDtzV9ePgRIHj2CqPJy0hiPjaTOAkHuLA6PQRV4n3JtnjUp",
	"dze7/lmlz05ZrW0J2eg4eU2Zod5Y2ViYgRjBOyKM9ZyWmWddeTWXya9UPlaQybkt8VJDyofUBwoROReC",
	"i65lhJ5YkdobQkBKvIDGkRW57PLr6T7eP06n1y8LlTNOnksamD0rKOeI46MTX5LQM085U5iyfYZYTeaM",
	"g7zkKqO2R2J5/LpVWKXto4sdfoPZAjZp1MeZVYDmPIr40w0QKiC0nYbNsmcJmGSNB79mPTD4BHenuOXQ",
	"2p6q+cxs4u+8Nq2WvDT0j3OdeD6eT85QgK6vbvWv6z/Nv5Pp6UcUoLPzT+dTna2urqcXV5e33oVVJD9b",
	"37/RtQKjbFFTVds4kdd7h8Pjw5NBc6GZinJNlApatnYvfP5kmIFgF12rydos2rCmist4TXvTIrxuDzhS",
	"S71sqTBIgBGbTFLTdOFPekECC4EJGD7ZA9MPfcBfsJCS7rmCtksTEZZqKjCTZt0uLZh1K60NHZ4AA9Jl",
	"fQmPICq9q1BQRUMceYGSVdg1zXVpRDyTKuZjWHdbhHZJhxdHEA92PpP4BFjC31w8/FpF1ROmqtWu+dD1",
	"7OadnLtui2rJ3XZ2Qc3s0jqZG915Q9+5hWJWzuvFgtNt4tu40hUEziSEqaKP8MFui2tUuUV7gbvKbRqG",
	"IOVOy2hfuZpJEI/d1NKx31LEgG3u4UbprY253P19SNYgsyGpT61Zk2z/Rv36DbV2anj9vpu3AHJPMe5e",
	"bjz/b9bt1qzTZQ3pZpq+iJgVbz+n1+dGYleeLe67U1Devd7K5WhfBlSyx2pzl9OthntxcPWVVhuAuJL6",
	"0PdsqwmVoaAxZTiLqjFOEs20fqcB87PqaWcGNrDUyebZ1dsYVDNhenrtcfzMIp4v7Zm0sXtdIjO4mqPx",
	"lwZ8PTysgu1zvGxsn+LBZnWXo38DMo3UJNSblgjIAuLu+xNh1uhgeXbbn8d/HIaQKLN5Iqk9Z4fmAr8g",
	"WixZa2FWxvfm3HsXydq7qUPugiWpKncq8rBf16rwSthOrpcpEJdn7yRvlYNVg3QbNBvEtHh2b7xNpNQP",
	"OLvGUgLx51FC8YJxqWh4i+MkqpYOx0NfoxWE4OKUk9JGdZ3cbDFzb0bZEpNBqIrfKlq/SwRXPORR8cBa",
	"9H1MZWys1vYx3N96aeenCpN72wopPdU0vic0a38rLBag7gkwCtlBg7n4cq84v4/0S2/ppaOGXHas9bEC",
	"Fj77C5Ny99m/x9Bb7Wm7myEB4lmNvm4p1tdBx7//3kQ8X67N0VbH5idPVcjjckfJ2qUtgrytjbWBTHVm",
	"XLRxy9JweyrVPkaLtMMmTXTcyKhIXnI1mSt7RLZDiemEfstpyV5cpkrGu0a/ap8bFhR4Q4fr8p6YURvA",
	"/ubioWtt2cn+u9V+O29y2ltFuASSRkA+cNHBMPZ888BrK6U61mV7c5NSf5PAuTTYqalDoMXRVsiFgMjZ",
	"/DaMt9cInTznRvL8GK59ineO7jy7Dtk54h75t52KqqgNGio7qHcPFw4EzEEAC5tDh7Jn6JZawX5gdVHF",
	"ukbV1UjcrY+ni4Cd0yJhcue5cyqkev+sYOcVzLnRTnNXHiSzize/9gVT91SymyCFe7R3nZqOTfH+hStV",
	"d/jZ4PUiPgA8+9Fd7hHtdjy+5PYQpuOVn2oDUu/6vVUXF2o7qifHx4fHTa08CYzsJt9+D2r9B64G00z2",
	"jPf8lNVjAEa8MBVUPd/qhJHtJ0lM2XvAwpZ4M/PXh5xdnuBvKWT51rRN7IC175rGzSqw105evM7KdLHn",
	"3LSQSjfvJ9cXvTkXPbWE3j9UMv4IvawgoGzRCzlTgke9JMIMepiRHk/VjKeM9Axn8l2RSsYonz+5vkDO",
	"5Ws0eDd8N9DCfJWcGYzwGcWRsXnDoBz3+/rdgc2477hY9InAc9UfDUaDg+EoS8XZgSVOKBqjw3fDdyNz",
	"x08tDeT9x2HfMHUAxSXrAxPD7KcVmadozytKiS1Xs7P+Kkj1Pru8UvM1RLevIJrvgq/KZpkdYZY+0RgN",
	"hq/GkFd2zzcaV8zml55NC+b9HKeRqiNQcOx8+bH2FdMaLHnJl7uV9i6sS4ovKMYMZ32UOz3Pp90tenXu",
	"/+1JkZ4bhm+sufLlO4/KzIuec1/tFZTmqMioo6Kd/tL91MSvm+JrlH2qp/LdSyvVHG3Gx2KFXtGjfR3L",
	"d+N62fK9sGad0PEsb+H6of0ziTgmTs9Q7gneja5yK4AHe6O/0Xv1fGQG4sDC2NvovP4UnT5x8TA2W/F6",
	"hZoLN8aWTQtlP8rcuNXzM5Rp5POozTBHenn/74BBqgSOeqYX0XsyswK/817ynqaGFZ1FdmhvBnMuoJc3",
	"qN9Y76VTz20FiXOiu78ipPr51Runr0JGn9Kzd73sHPunlBtZHdyorPwCzD51VfkS7Y1VlUvo0VT26n9C",
	"Uf0fRS9zpakvwKOzP0C5CttTSGtG7G2RCkqfltecyq+H9NefnpuD8jqU+zhU9BEOqHOttw71iRmaL5xP",
	"2KMOChq+0tgw01sPqU8heHPor6+3ZXHdp8FJsus2+3eV/F5PfYhZFjd/fin8pe3yNqaRvBu8zzRS+dTz",
	"jdNILqFHx9mr10wjbhmWqqVOF2aAeMx1ab7SQH3kaD//rNxOWQXFb8cqnKe2vlvdrf4bAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
