//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentCapability.
const (
	AgentCapabilityDns                 AgentCapability = "dns"
	AgentCapabilityHttp                AgentCapability = "http"
	AgentCapabilityKubernetesDiscovery AgentCapability = "kubernetes-discovery"
	AgentCapabilityKubernetesWatch     AgentCapability = "kubernetes-watch"
	AgentCapabilityTcp                 AgentCapability = "tcp"
)

// Valid indicates whether the value is a known member of the AgentCapability enum.
func (e AgentCapability) Valid() bool {
	switch e {
	case AgentCapabilityDns:
		return true
	case AgentCapabilityHttp:
		return true
	case AgentCapabilityKubernetesDiscovery:
		return true
	case AgentCapabilityKubernetesWatch:
		return true
	case AgentCapabilityTcp:
		return true
	default:
		return false
	}
}

// Defines values for HTTPProbeMethod.
const (
	DELETE  HTTPProbeMethod = "DELETE"
	GET     HTTPProbeMethod = "GET"
	HEAD    HTTPProbeMethod = "HEAD"
	OPTIONS HTTPProbeMethod = "OPTIONS"
	PATCH   HTTPProbeMethod = "PATCH"
	POST    HTTPProbeMethod = "POST"
	PUT     HTTPProbeMethod = "PUT"
)

// Valid indicates whether the value is a known member of the HTTPProbeMethod enum.
func (e HTTPProbeMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case HEAD:
		return true
	case OPTIONS:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for HealthState.
const (
	Degraded HealthState = "degraded"
	Down     HealthState = "down"
	Pending  HealthState = "pending"
	Unknown  HealthState = "unknown"
	Up       HealthState = "up"
)

// Valid indicates whether the value is a known member of the HealthState enum.
func (e HealthState) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Down:
		return true
	case Pending:
		return true
	case Unknown:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for IncidentSeverity.
const (
	Critical IncidentSeverity = "critical"
)

// Valid indicates whether the value is a known member of the IncidentSeverity enum.
func (e IncidentSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	default:
		return false
	}
}

// Defines values for IncidentState.
const (
	Open     IncidentState = "open"
	Resolved IncidentState = "resolved"
)

// Valid indicates whether the value is a known member of the IncidentState enum.
func (e IncidentState) Valid() bool {
	switch e {
	case Open:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for MonitorKind.
const (
	MonitorKindHttp MonitorKind = "http"
)

// Valid indicates whether the value is a known member of the MonitorKind enum.
func (e MonitorKind) Valid() bool {
	switch e {
	case MonitorKindHttp:
		return true
	default:
		return false
	}
}

// Defines values for ProbeResultAcknowledgementStatus.
const (
	Accepted  ProbeResultAcknowledgementStatus = "accepted"
	Duplicate ProbeResultAcknowledgementStatus = "duplicate"
)

// Valid indicates whether the value is a known member of the ProbeResultAcknowledgementStatus enum.
func (e ProbeResultAcknowledgementStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Duplicate:
		return true
	default:
		return false
	}
}

// Defines values for ProbeResultInputErrorCode.
const (
	BodyMismatch      ProbeResultInputErrorCode = "body_mismatch"
	ConnectError      ProbeResultInputErrorCode = "connect_error"
	DnsError          ProbeResultInputErrorCode = "dns_error"
	DnsMismatch       ProbeResultInputErrorCode = "dns_mismatch"
	Empty             ProbeResultInputErrorCode = ""
	ProtocolError     ProbeResultInputErrorCode = "protocol_error"
	ResponseTooLarge  ProbeResultInputErrorCode = "response_too_large"
	StatusMismatch    ProbeResultInputErrorCode = "status_mismatch"
	TargetDenied      ProbeResultInputErrorCode = "target_denied"
	TcpExpectMismatch ProbeResultInputErrorCode = "tcp_expect_mismatch"
	Timeout           ProbeResultInputErrorCode = "timeout"
	TlsError          ProbeResultInputErrorCode = "tls_error"
	TlsExpiring       ProbeResultInputErrorCode = "tls_expiring"
)

// Valid indicates whether the value is a known member of the ProbeResultInputErrorCode enum.
func (e ProbeResultInputErrorCode) Valid() bool {
	switch e {
	case BodyMismatch:
		return true
	case ConnectError:
		return true
	case DnsError:
		return true
	case DnsMismatch:
		return true
	case Empty:
		return true
	case ProtocolError:
		return true
	case ResponseTooLarge:
		return true
	case StatusMismatch:
		return true
	case TargetDenied:
		return true
	case TcpExpectMismatch:
		return true
	case Timeout:
		return true
	case TlsError:
		return true
	case TlsExpiring:
		return true
	default:
		return false
	}
}

// Defines values for ProbeResultInputOutcome.
const (
	Failed ProbeResultInputOutcome = "failed"
	Passed ProbeResultInputOutcome = "passed"
)

// Valid indicates whether the value is a known member of the ProbeResultInputOutcome enum.
func (e ProbeResultInputOutcome) Valid() bool {
	switch e {
	case Failed:
		return true
	case Passed:
		return true
	default:
		return false
	}
}

// AgentCapability defines model for AgentCapability.
type AgentCapability string

// AgentEnrollmentToken defines model for AgentEnrollmentToken.
type AgentEnrollmentToken struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// AgentHeartbeat defines model for AgentHeartbeat.
type AgentHeartbeat struct {
	Capabilities         []AgentCapability `json:"capabilities"`
	CredentialGeneration int64             `json:"credentialGeneration"`
	Version              string            `json:"version"`
}

// CreateAgentEnrollmentTokenRequest defines model for CreateAgentEnrollmentTokenRequest.
type CreateAgentEnrollmentTokenRequest struct {
	ExpiresInSeconds int32              `json:"expiresInSeconds"`
	LocationId       openapi_types.UUID `json:"locationId"`
}

// CreateLocationRequest defines model for CreateLocationRequest.
type CreateLocationRequest struct {
	Name string `json:"name"`
}

// CreateMonitorRequest defines model for CreateMonitorRequest.
type CreateMonitorRequest struct {
	FailureThreshold  int32              `json:"failureThreshold"`
	Http              HTTPProbe          `json:"http"`
	IntervalSeconds   int32              `json:"intervalSeconds"`
	LocationId        openapi_types.UUID `json:"locationId"`
	Name              string             `json:"name"`
	RecoveryThreshold int32              `json:"recoveryThreshold"`
	RequiredLocation  bool               `json:"requiredLocation"`
	TimeoutMillis     int32              `json:"timeoutMillis"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// EnrollAgentRequest defines model for EnrollAgentRequest.
type EnrollAgentRequest struct {
	Capabilities []AgentCapability `json:"capabilities"`
	Name         string            `json:"name"`
	Token        *string           `json:"token,omitempty"`
}

// EnrolledAgent defines model for EnrolledAgent.
type EnrolledAgent struct {
	AgentId              openapi_types.UUID `json:"agentId"`
	Credential           string             `json:"credential"`
	CredentialGeneration int64              `json:"credentialGeneration"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// HTTPProbe defines model for HTTPProbe.
type HTTPProbe struct {
	BodyContains    string          `json:"bodyContains"`
	ExpectedStatus  int32           `json:"expectedStatus"`
	FollowRedirects bool            `json:"followRedirects"`
	Method          HTTPProbeMethod `json:"method"`
	Url             string          `json:"url"`
}

// HTTPProbeMethod defines model for HTTPProbe.Method.
type HTTPProbeMethod string

// HTTPWork defines model for HTTPWork.
type HTTPWork struct {
	Http          HTTPProbe          `json:"http"`
	LeaseToken    string             `json:"leaseToken"`
	MonitorId     openapi_types.UUID `json:"monitorId"`
	RunId         openapi_types.UUID `json:"runId"`
	ScheduledFor  time.Time          `json:"scheduledFor"`
	TimeoutMillis int32              `json:"timeoutMillis"`
}

// HealthState defines model for HealthState.
type HealthState string

// Incident defines model for Incident.
type Incident struct {
	Id               openapi_types.UUID `json:"id"`
	LastTransitionAt time.Time          `json:"lastTransitionAt"`
	MonitorId        openapi_types.UUID `json:"monitorId"`
	OpenedAt         time.Time          `json:"openedAt"`
	Severity         IncidentSeverity   `json:"severity"`
	State            IncidentState      `json:"state"`
}

// IncidentSeverity defines model for Incident.Severity.
type IncidentSeverity string

// IncidentState defines model for Incident.State.
type IncidentState string

// LeaseWorkRequest defines model for LeaseWorkRequest.
type LeaseWorkRequest struct {
	Capabilities []AgentCapability `json:"capabilities"`
	WaitSeconds  int32             `json:"waitSeconds"`
}

// Location defines model for Location.
type Location struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// LocationHealth defines model for LocationHealth.
type LocationHealth struct {
	ConsecutiveFailures  int32              `json:"consecutiveFailures"`
	ConsecutiveSuccesses int32              `json:"consecutiveSuccesses"`
	LastObservedAt       time.Time          `json:"lastObservedAt"`
	LocationId           openapi_types.UUID `json:"locationId"`
	State                HealthState        `json:"state"`
}

// Monitor defines model for Monitor.
type Monitor struct {
	CreatedAt         time.Time          `json:"createdAt"`
	FailureThreshold  int32              `json:"failureThreshold"`
	Http              HTTPProbe          `json:"http"`
	Id                openapi_types.UUID `json:"id"`
	IntervalSeconds   int32              `json:"intervalSeconds"`
	Kind              MonitorKind        `json:"kind"`
	LocationId        openapi_types.UUID `json:"locationId"`
	Name              string             `json:"name"`
	RecoveryThreshold int32              `json:"recoveryThreshold"`
	RequiredLocation  bool               `json:"requiredLocation"`
	TimeoutMillis     int32              `json:"timeoutMillis"`
	UpdatedAt         time.Time          `json:"updatedAt"`
}

// MonitorKind defines model for Monitor.Kind.
type MonitorKind string

// MonitorHealth defines model for MonitorHealth.
type MonitorHealth struct {
	LastTransitionAt time.Time          `json:"lastTransitionAt"`
	Locations        []LocationHealth   `json:"locations"`
	MonitorId        openapi_types.UUID `json:"monitorId"`
	State            HealthState        `json:"state"`
}

// ProbeResultAcknowledgement defines model for ProbeResultAcknowledgement.
type ProbeResultAcknowledgement struct {
	ResultId openapi_types.UUID               `json:"resultId"`
	Status   ProbeResultAcknowledgementStatus `json:"status"`
}

// ProbeResultAcknowledgementStatus defines model for ProbeResultAcknowledgement.Status.
type ProbeResultAcknowledgementStatus string

// ProbeResultBatch defines model for ProbeResultBatch.
type ProbeResultBatch struct {
	Results []ProbeResultInput `json:"results"`
}

// ProbeResultBatchAcknowledgement defines model for ProbeResultBatchAcknowledgement.
type ProbeResultBatchAcknowledgement struct {
	Acknowledgements []ProbeResultAcknowledgement `json:"acknowledgements"`
}

// ProbeResultInput defines model for ProbeResultInput.
type ProbeResultInput struct {
	BodyAssertionPassed bool                      `json:"bodyAssertionPassed"`
	DiagnosticSample    string                    `json:"diagnosticSample"`
	ErrorCode           ProbeResultInputErrorCode `json:"errorCode"`
	FinishedAt          time.Time                 `json:"finishedAt"`
	LatencyMillis       int64                     `json:"latencyMillis"`
	LeaseToken          string                    `json:"leaseToken"`
	ObservedStatus      int32                     `json:"observedStatus"`
	ObservedValues      *[]string                 `json:"observedValues,omitempty"`
	Outcome             ProbeResultInputOutcome   `json:"outcome"`
	ProtocolTimings     *ProtocolTimings          `json:"protocolTimings,omitempty"`
	ResultId            openapi_types.UUID        `json:"resultId"`
	RunId               openapi_types.UUID        `json:"runId"`
	StartedAt           time.Time                 `json:"startedAt"`
	TlsNotAfter         *time.Time                `json:"tlsNotAfter,omitempty"`
}

// ProbeResultInputErrorCode defines model for ProbeResultInput.ErrorCode.
type ProbeResultInputErrorCode string

// ProbeResultInputOutcome defines model for ProbeResultInput.Outcome.
type ProbeResultInputOutcome string

// Problem defines model for Problem.
type Problem struct {
	Code          string        `json:"code"`
	CorrelationId string        `json:"correlationId"`
	Detail        *string       `json:"detail,omitempty"`
	FieldErrors   *[]FieldError `json:"fieldErrors,omitempty"`
	Status        int32         `json:"status"`
	Title         string        `json:"title"`
	Type          string        `json:"type"`
}

// ProtocolTimings defines model for ProtocolTimings.
type ProtocolTimings struct {
	ConnectMillis   *int64 `json:"connectMillis,omitempty"`
	DnsMillis       *int64 `json:"dnsMillis,omitempty"`
	FirstByteMillis *int64 `json:"firstByteMillis,omitempty"`
	TlsMillis       *int64 `json:"tlsMillis,omitempty"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// MonitorID defines model for MonitorID.
type MonitorID = openapi_types.UUID

// CreateAgentEnrollmentTokenJSONRequestBody defines body for CreateAgentEnrollmentToken for application/json ContentType.
type CreateAgentEnrollmentTokenJSONRequestBody = CreateAgentEnrollmentTokenRequest

// EnrollAgentJSONRequestBody defines body for EnrollAgent for application/json ContentType.
type EnrollAgentJSONRequestBody = EnrollAgentRequest

// HeartbeatAgentJSONRequestBody defines body for HeartbeatAgent for application/json ContentType.
type HeartbeatAgentJSONRequestBody = AgentHeartbeat

// UploadProbeResultsJSONRequestBody defines body for UploadProbeResults for application/json ContentType.
type UploadProbeResultsJSONRequestBody = ProbeResultBatch

// LeaseAgentWorkJSONRequestBody defines body for LeaseAgentWork for application/json ContentType.
type LeaseAgentWorkJSONRequestBody = LeaseWorkRequest

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = CreateLocationRequest

// CreateMonitorJSONRequestBody defines body for CreateMonitor for application/json ContentType.
type CreateMonitorJSONRequestBody = CreateMonitorRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/agent-enrollment-tokens)
	CreateAgentEnrollmentToken(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent-enrollments)
	EnrollAgent(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent/heartbeat)
	HeartbeatAgent(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent/results:batch)
	UploadProbeResults(w http.ResponseWriter, r *http.Request)

	// (POST /v1/agent/work:lease)
	LeaseAgentWork(w http.ResponseWriter, r *http.Request)

	// (POST /v1/locations)
	CreateLocation(w http.ResponseWriter, r *http.Request)

	// (POST /v1/monitors)
	CreateMonitor(w http.ResponseWriter, r *http.Request)

	// (GET /v1/monitors/{monitorId})
	GetMonitor(w http.ResponseWriter, r *http.Request, monitorId MonitorID)

	// (GET /v1/monitors/{monitorId}/active-incident)
	GetActiveMonitorIncident(w http.ResponseWriter, r *http.Request, monitorId MonitorID)

	// (GET /v1/monitors/{monitorId}/health)
	GetMonitorHealth(w http.ResponseWriter, r *http.Request, monitorId MonitorID)

	// (POST /v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAgentEnrollmentToken operation middleware
func (siw *ServerInterfaceWrapper) CreateAgentEnrollmentToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgentEnrollmentToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrollAgent operation middleware
func (siw *ServerInterfaceWrapper) EnrollAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrollAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeartbeatAgent operation middleware
func (siw *ServerInterfaceWrapper) HeartbeatAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeartbeatAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadProbeResults operation middleware
func (siw *ServerInterfaceWrapper) UploadProbeResults(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadProbeResults(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeaseAgentWork operation middleware
func (siw *ServerInterfaceWrapper) LeaseAgentWork(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeaseAgentWork(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLocation operation middleware
func (siw *ServerInterfaceWrapper) CreateLocation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLocation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMonitor operation middleware
func (siw *ServerInterfaceWrapper) CreateMonitor(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMonitor(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonitor operation middleware
func (siw *ServerInterfaceWrapper) GetMonitor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "monitorId" -------------
	var monitorId MonitorID

	err = runtime.BindStyledParameterWithOptions("simple", "monitorId", r.PathValue("monitorId"), &monitorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "monitorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonitor(w, r, monitorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActiveMonitorIncident operation middleware
func (siw *ServerInterfaceWrapper) GetActiveMonitorIncident(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "monitorId" -------------
	var monitorId MonitorID

	err = runtime.BindStyledParameterWithOptions("simple", "monitorId", r.PathValue("monitorId"), &monitorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "monitorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActiveMonitorIncident(w, r, monitorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonitorHealth operation middleware
func (siw *ServerInterfaceWrapper) GetMonitorHealth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "monitorId" -------------
	var monitorId MonitorID

	err = runtime.BindStyledParameterWithOptions("simple", "monitorId", r.PathValue("monitorId"), &monitorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "monitorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonitorHealth(w, r, monitorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/locations", wrapper.CreateLocation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/monitors", wrapper.CreateMonitor)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/monitors/{monitorId}", wrapper.GetMonitor)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent-enrollment-tokens", wrapper.CreateAgentEnrollmentToken)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent-enrollments", wrapper.EnrollAgent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent/heartbeat", wrapper.HeartbeatAgent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent/work:lease", wrapper.LeaseAgentWork)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agent/results:batch", wrapper.UploadProbeResults)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/monitors/{monitorId}/health", wrapper.GetMonitorHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/monitors/{monitorId}/active-incident", wrapper.GetActiveMonitorIncident)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type CreateAgentEnrollmentTokenRequestObject struct {
	Body *CreateAgentEnrollmentTokenJSONRequestBody
}

type CreateAgentEnrollmentTokenResponseObject interface {
	VisitCreateAgentEnrollmentTokenResponse(w http.ResponseWriter) error
}

type CreateAgentEnrollmentToken201JSONResponse AgentEnrollmentToken

func (response CreateAgentEnrollmentToken201JSONResponse) VisitCreateAgentEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentEnrollmentTokendefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateAgentEnrollmentTokendefaultApplicationProblemPlusJSONResponse) VisitCreateAgentEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollAgentRequestObject struct {
	Body *EnrollAgentJSONRequestBody
}

type EnrollAgentResponseObject interface {
	VisitEnrollAgentResponse(w http.ResponseWriter) error
}

type EnrollAgent201JSONResponse EnrolledAgent

func (response EnrollAgent201JSONResponse) VisitEnrollAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollAgentdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response EnrollAgentdefaultApplicationProblemPlusJSONResponse) VisitEnrollAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type HeartbeatAgentRequestObject struct {
	Body *HeartbeatAgentJSONRequestBody
}

type HeartbeatAgentResponseObject interface {
	VisitHeartbeatAgentResponse(w http.ResponseWriter) error
}

type HeartbeatAgent204Response struct {
}

func (response HeartbeatAgent204Response) VisitHeartbeatAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type HeartbeatAgentdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response HeartbeatAgentdefaultApplicationProblemPlusJSONResponse) VisitHeartbeatAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UploadProbeResultsRequestObject struct {
	Body *UploadProbeResultsJSONRequestBody
}

type UploadProbeResultsResponseObject interface {
	VisitUploadProbeResultsResponse(w http.ResponseWriter) error
}

type UploadProbeResults200JSONResponse ProbeResultBatchAcknowledgement

func (response UploadProbeResults200JSONResponse) VisitUploadProbeResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UploadProbeResultsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UploadProbeResultsdefaultApplicationProblemPlusJSONResponse) VisitUploadProbeResultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type LeaseAgentWorkRequestObject struct {
	Body *LeaseAgentWorkJSONRequestBody
}

type LeaseAgentWorkResponseObject interface {
	VisitLeaseAgentWorkResponse(w http.ResponseWriter) error
}

type LeaseAgentWork200JSONResponse HTTPWork

func (response LeaseAgentWork200JSONResponse) VisitLeaseAgentWorkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LeaseAgentWork204Response struct {
}

func (response LeaseAgentWork204Response) VisitLeaseAgentWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LeaseAgentWorkdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response LeaseAgentWorkdefaultApplicationProblemPlusJSONResponse) VisitLeaseAgentWorkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocationRequestObject struct {
	Body *CreateLocationJSONRequestBody
}

type CreateLocationResponseObject interface {
	VisitCreateLocationResponse(w http.ResponseWriter) error
}

type CreateLocation201JSONResponse Location

func (response CreateLocation201JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateLocationdefaultApplicationProblemPlusJSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMonitorRequestObject struct {
	Body *CreateMonitorJSONRequestBody
}

type CreateMonitorResponseObject interface {
	VisitCreateMonitorResponse(w http.ResponseWriter) error
}

type CreateMonitor201JSONResponse Monitor

func (response CreateMonitor201JSONResponse) VisitCreateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMonitordefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateMonitordefaultApplicationProblemPlusJSONResponse) VisitCreateMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitorRequestObject struct {
	MonitorId MonitorID `json:"monitorId"`
}

type GetMonitorResponseObject interface {
	VisitGetMonitorResponse(w http.ResponseWriter) error
}

type GetMonitor200JSONResponse Monitor

func (response GetMonitor200JSONResponse) VisitGetMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitordefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMonitordefaultApplicationProblemPlusJSONResponse) VisitGetMonitorResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetActiveMonitorIncidentRequestObject struct {
	MonitorId MonitorID `json:"monitorId"`
}

type GetActiveMonitorIncidentResponseObject interface {
	VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error
}

type GetActiveMonitorIncident200JSONResponse Incident

func (response GetActiveMonitorIncident200JSONResponse) VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetActiveMonitorIncident204Response struct {
}

func (response GetActiveMonitorIncident204Response) VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetActiveMonitorIncidentdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetActiveMonitorIncidentdefaultApplicationProblemPlusJSONResponse) VisitGetActiveMonitorIncidentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitorHealthRequestObject struct {
	MonitorId MonitorID `json:"monitorId"`
}

type GetMonitorHealthResponseObject interface {
	VisitGetMonitorHealthResponse(w http.ResponseWriter) error
}

type GetMonitorHealth200JSONResponse MonitorHealth

func (response GetMonitorHealth200JSONResponse) VisitGetMonitorHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMonitorHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMonitorHealthdefaultApplicationProblemPlusJSONResponse) VisitGetMonitorHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse Session

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessiondefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateSessiondefaultApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /v1/agent-enrollment-tokens)
	CreateAgentEnrollmentToken(ctx context.Context, request CreateAgentEnrollmentTokenRequestObject) (CreateAgentEnrollmentTokenResponseObject, error)

	// (POST /v1/agent-enrollments)
	EnrollAgent(ctx context.Context, request EnrollAgentRequestObject) (EnrollAgentResponseObject, error)

	// (POST /v1/agent/heartbeat)
	HeartbeatAgent(ctx context.Context, request HeartbeatAgentRequestObject) (HeartbeatAgentResponseObject, error)

	// (POST /v1/agent/results:batch)
	UploadProbeResults(ctx context.Context, request UploadProbeResultsRequestObject) (UploadProbeResultsResponseObject, error)

	// (POST /v1/agent/work:lease)
	LeaseAgentWork(ctx context.Context, request LeaseAgentWorkRequestObject) (LeaseAgentWorkResponseObject, error)

	// (POST /v1/locations)
	CreateLocation(ctx context.Context, request CreateLocationRequestObject) (CreateLocationResponseObject, error)

	// (POST /v1/monitors)
	CreateMonitor(ctx context.Context, request CreateMonitorRequestObject) (CreateMonitorResponseObject, error)

	// (GET /v1/monitors/{monitorId})
	GetMonitor(ctx context.Context, request GetMonitorRequestObject) (GetMonitorResponseObject, error)

	// (GET /v1/monitors/{monitorId}/active-incident)
	GetActiveMonitorIncident(ctx context.Context, request GetActiveMonitorIncidentRequestObject) (GetActiveMonitorIncidentResponseObject, error)

	// (GET /v1/monitors/{monitorId}/health)
	GetMonitorHealth(ctx context.Context, request GetMonitorHealthRequestObject) (GetMonitorHealthResponseObject, error)

	// (POST /v1/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAgentEnrollmentToken operation middleware
func (sh *strictHandler) CreateAgentEnrollmentToken(w http.ResponseWriter, r *http.Request) {
	var request CreateAgentEnrollmentTokenRequestObject

	var body CreateAgentEnrollmentTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAgentEnrollmentToken(ctx, request.(CreateAgentEnrollmentTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAgentEnrollmentToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAgentEnrollmentTokenResponseObject); ok {
		if err := validResponse.VisitCreateAgentEnrollmentTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnrollAgent operation middleware
func (sh *strictHandler) EnrollAgent(w http.ResponseWriter, r *http.Request) {
	var request EnrollAgentRequestObject

	var body EnrollAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnrollAgent(ctx, request.(EnrollAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrollAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnrollAgentResponseObject); ok {
		if err := validResponse.VisitEnrollAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeartbeatAgent operation middleware
func (sh *strictHandler) HeartbeatAgent(w http.ResponseWriter, r *http.Request) {
	var request HeartbeatAgentRequestObject

	var body HeartbeatAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeartbeatAgent(ctx, request.(HeartbeatAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeartbeatAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeartbeatAgentResponseObject); ok {
		if err := validResponse.VisitHeartbeatAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadProbeResults operation middleware
func (sh *strictHandler) UploadProbeResults(w http.ResponseWriter, r *http.Request) {
	var request UploadProbeResultsRequestObject

	var body UploadProbeResultsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadProbeResults(ctx, request.(UploadProbeResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadProbeResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadProbeResultsResponseObject); ok {
		if err := validResponse.VisitUploadProbeResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LeaseAgentWork operation middleware
func (sh *strictHandler) LeaseAgentWork(w http.ResponseWriter, r *http.Request) {
	var request LeaseAgentWorkRequestObject

	var body LeaseAgentWorkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LeaseAgentWork(ctx, request.(LeaseAgentWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaseAgentWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LeaseAgentWorkResponseObject); ok {
		if err := validResponse.VisitLeaseAgentWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateLocation operation middleware
func (sh *strictHandler) CreateLocation(w http.ResponseWriter, r *http.Request) {
	var request CreateLocationRequestObject

	var body CreateLocationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateLocation(ctx, request.(CreateLocationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateLocation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateLocationResponseObject); ok {
		if err := validResponse.VisitCreateLocationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMonitor operation middleware
func (sh *strictHandler) CreateMonitor(w http.ResponseWriter, r *http.Request) {
	var request CreateMonitorRequestObject

	var body CreateMonitorJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMonitor(ctx, request.(CreateMonitorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMonitor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMonitorResponseObject); ok {
		if err := validResponse.VisitCreateMonitorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMonitor operation middleware
func (sh *strictHandler) GetMonitor(w http.ResponseWriter, r *http.Request, monitorId MonitorID) {
	var request GetMonitorRequestObject

	request.MonitorId = monitorId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitor(ctx, request.(GetMonitorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMonitorResponseObject); ok {
		if err := validResponse.VisitGetMonitorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetActiveMonitorIncident operation middleware
func (sh *strictHandler) GetActiveMonitorIncident(w http.ResponseWriter, r *http.Request, monitorId MonitorID) {
	var request GetActiveMonitorIncidentRequestObject

	request.MonitorId = monitorId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetActiveMonitorIncident(ctx, request.(GetActiveMonitorIncidentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetActiveMonitorIncident")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetActiveMonitorIncidentResponseObject); ok {
		if err := validResponse.VisitGetActiveMonitorIncidentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMonitorHealth operation middleware
func (sh *strictHandler) GetMonitorHealth(w http.ResponseWriter, r *http.Request, monitorId MonitorID) {
	var request GetMonitorHealthRequestObject

	request.MonitorId = monitorId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitorHealth(ctx, request.(GetMonitorHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitorHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMonitorHealthResponseObject); ok {
		if err := validResponse.VisitGetMonitorHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fvdbts6En4Vg7t3q8Q/TYtT36Vt2gboaYLGZ3eBIAhocWyzoUiVpJwEhd99QVKSKYm2LCdOT7E3QSTx",
	"Z+b7hsPhcPwTxSJJBQeuFRr/RCmWOAEN0j79KTjVQp5/MA+UozFKsV6gCHGcABqjJP9OUIQk/MioBILG",
	"WmYQIRUvIMGm40zIBGs0RllGTUv9mJrOSkvK52i1WpnOKhVcgZ31Uoopg8T8GwuugWvzL05TRmOsqeD9",
	"1LX413cluPm2nuufEmZojP7RX6vVd19VvxjXzkhAxZKmZjg0LqbsEdCYMoVMi7ybGfV0Dly/xymeUkb1",
	"o3kFPEvQ+BottE6NTrH5S7hCEbrLpiA5aFBHhKpYLEE+Vl/fYx0v0E0DisjNdMalYCwBrifiDqyGmBBq",
	"ZMXsUooUpKYGqxlmCiKUeq9+InhIqQR1qivYE6zhSNMEUGBWXUyTUP4F+Fwv0PjVqMmUz/J13ivyJlxr",
	"JKbfIdalRp8BSz0FrDvqEheY589UQ6LaeK6ztYqMXueu67AUEUuJDS8Zpz8yyD8b211FKJZAgGuK2Sfg",
	"ILEzEw9OyvWbE2QHpomxhPW4lGuYgzTTLkGqvGeCHwpk35xEPtDDNpyLUTaIFVVRCnHwXgLWELKtb/Aj",
	"A6X3M7FzfgWx4ETVoXk1MtDgBwfNH29OBgMPqjeDEFZMuMV9TnbxGVWEvL5RU7jNiHzJ++2HgnOCFWqH",
	"o0E3bu0YmwXMHfB+8s0wZZmEyUKCWghGtrM0rHAUNGfr61oW3+fJ5NJ4UzAdTF+5xGwvM3n9ZCuJQhSN",
	"Bm0UGYac134+6ArOC4szA+atpkIwwNz6YZqAyPSflDHagtZwNBhUpx0EllXI2pq01CeOmqYTwiSqrruG",
	"irnBbLbuK1Bq79UHCaasgpF7E1XIfn0SoDfFSt0LSeqLdzCqeuY/6n0jdC+phgvOHvOtogZwIUI5Q0h5",
	"54KtN95P9V+1K+7l8HaNLlqxLcKN3IhbNz0HMxCreEeEsemzo49Zb8rtEdQzRRY1ZAppK7JsmCqE1EcK",
	"jJxJKWTXHcZ0rGkdsoAElMJzaG1Z08sNv+4ekn2933QTfSrI43vBNaZc1Wz6ZPD2TUAJeEgh1kCuNNZZ",
	"i3d+/fZtm2uO0EwwJu6/AaESYnf8am4JCeiFIP6J49PZBEXo89npBxShy4sr83T5l/17Onn/GUXow9mX",
	"s8kZitDF5eT84utV8KSRyar3zCSt+s4gDDWGcuncaA2IoirKTY03EfofIe868tk5NmGAFUx2O/hE3kl3",
	"F5cgs10DFCMayRiQj27x7XheO3Cc4OSvYBRVDvsVsZvhw8Z9/zNgphfGPMA36RQ4cXtAZo/R4t5MSGAu",
	"MQFrXvyOm5chQz7nMSXdXTzdjSCGlZ5IzJUdt8uhupvJiBQ4kC7jK1iCrGUjYkk1jTELAqXqsJs5beCm",
	"BFsCCXSq2YUVvWIHdkhPFk+RAHYhk/hibMws+N8rFrrHVO90rHnlL772peePu0OQ458nuqBm4+9O5kb3",
	"PnF1PhTbkYswr5R0m/rOr3QFQXAFcabpEj66884GKrewF/mjXGVxDErtNYxZKxdTBXLZjZaOB+LSB2zd",
	"Jz0vvTXVUiz/EJIbkGloGqI1T3sc3qj/BimS3Xh7/kzKHeWkkci+ebqF/b+nXEwMQ7rZYcj9WXqiX5Ox",
	"8b2ur86WpbqXA94/tirU2H3Lr+0Uq9om3zlee7IjDYVRDUB8TUPoWzfyDVTG9GlsQmQGZA5J92hY2jE6",
	"6O5OwIXzwHEMqbahOsncPR20h5PlpOWQLTq+s/dm+2i2u6F4053zNLMiJPihCA5zB7AhVgxruJteTyMQ",
	"V3vvpW9dglWLdo05W9R0eHbP05wqZV4IfomVAhJ25ITiORdK0/gKJymr70Gvh6FjPUgp5HtBKseitXd1",
	"V7q3tpULaDjEunzWbP0tlUKLWLDyhbPo24SqxFqtS4b4z2Zo71HH6a1LoFTemjkeUprnSDWWc9C3BDgF",
	"58LdxfmtFuKWmY/BPXxGOVWLjpEl1sDjx/DOWE1RhiPaTgkWkUeE3bNrwcmL4f6NWVY7GLZn+tbLfTRo",
	"7hMi07FIqvkLZ5duFw4epNcGMqEJ5fNdlmWluSuS2N1Hd0hBaSw7hs2aqa9Cn840yD1jHM/1B5NNa6Eq",
	"xrtGv26fDQuKgq7DX/IBn7HJgeXlKJ0OlwR2yIzHQkpgXnzd0t4VqHge0F/jRRZ/d+fvZf4DEZHqvBZP",
	"whGxpprtgoZ7UU1KH0mYgQQetxuV/VrMVoofOS7qWG+gur5Gu+UTzPawt8MkXO3dd0al0u8eNew9gmb7",
	"zr4KIJlf7f7OpUs2xRpnkurHK7Nc8jiLJJS/Ayyd65va/z4WoooU/8ggT5DbEjnXYC25PWCtIndn9+Rx",
	"VjY1MBNmiGpF2+nleW8mZE8voPdfqrhYQi8/clA+78WCaylYL2WYQw9z0hOZnoqMk56VTB2XC2mMiv6n",
	"l+fIK2pCg+Ph8cAo810JbjHCHyhmBj0noBr3++bbkfM3x0LO+0Time6PBqPB0XCUO6I8bYxTisbo1fHw",
	"eGTv0PXCQt5fDvtWqCMoi5eOLIOuZFG4pLExpNKRbil5yg++oPQ7QR63VBl2qy5sr7FaVa0wTyRXSh9H",
	"g+GzCRTUPVD7eMHd6uq5RWG/z3DG9KYJSom9isr1WkHj69oqub5ZmdWFjUO9RgnmOD9f3Jh+IXa38OoV",
	"TxyIyEB5xgszV61cCFBmP/S8y/5nIM2jyNJRY6e/8Es4w9yUVZ6HpKdWT7oTNSdN/1iO0CtzF89j+b5f",
	"r1p+ENY8QzCeFqmNMLR/pUxg4p2l1YHgbWRbdgJ4cLD5GzmJQPE2yCMHY6+RkfglnN4LeTe2x5nNhNpr",
	"T2vLttjhMGQ27lZfmMyyliPAmpWN9EyT3r1tE4VX6lfRM0NjTacMbNPeFGZCQq/I0rwwyZXk87bow8ur",
	"Hy7iqNcwv/BeVeoYojj/1suvE35JbJEHva1kFXeOh+SqVs79wlQVGgaYyj/9LYjq/yyvRlZm9jkEOPsE",
	"2ifsQP6rHbGXRSqq/D7rOjzfukl//fut1c0WlPs41nQJR9SrpNqE+qltWgxcdDggB+UcoTjYCtNbN9m8",
	"heBm09+ft0V569qySPJbz8MvleJ6dbOLWZQXsL8V/soltFq3kSLxdchtpPa7iRfeRgoNAxznn55zG/HD",
	"sEwvzHZhG8hlwaUtZEZ95LFf/DbLdVlF5bNnFd5bF9+tblb/CwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
