.PHONY: generate test check storage-check dagger-ci

generate:
	go generate ./...
	go tool sqlc generate
	cd agent && GOWORK=off go generate ./...

test:
	go test ./...
	cd agent && GOWORK=off go test ./...

storage-check:
	go test -race ./integration -run 'TestStorageMatrix/(SQLite|TursoLocal)' -count=1

check: generate
	git diff --exit-code
	go tool vacuum lint -d api/openapi.yaml
	go tool sqlc diff
	go vet ./...
	$(MAKE) storage-check
	go test -race ./...
	cd agent && GOWORK=off go vet ./...
	cd agent && GOWORK=off go test -race ./...

dagger-ci:
	dagger call local-ci --source=. --run-nonce="$$(date +%s)-$$$$"
