.PHONY: generate test check

generate:
	go generate ./...
	cd agent && go generate ./...

test:
	go test ./...
	cd agent && GOWORK=off go test ./...

check: generate
	git diff --exit-code
	go vet ./...
	go test -race ./...
	cd agent && GOWORK=off go vet ./...
	cd agent && GOWORK=off go test -race ./...
