.PHONY: generate test check

generate:
	go generate ./...
	go tool sqlc generate
	cd agent && GOWORK=off go generate ./...

test:
	go test ./...
	cd agent && GOWORK=off go test ./...

check: generate
	git diff --exit-code
	go tool vacuum lint -d api/openapi.yaml
	go tool sqlc diff
	go vet ./...
	go test -race ./...
	cd agent && GOWORK=off go vet ./...
	cd agent && GOWORK=off go test -race ./...
