apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xisnove-edge.operatorServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xisnove-edge.labels" . | nindent 4 }}
automountServiceAccountToken: true
