{{- range $component := list "server" "ui" "agent" }}
{{- $values := index $.Values $component }}
{{- if and $values.serviceAccount.create (or (ne $component "agent") $.Values.agent.enabled) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if eq $component "server" }}{{ include "xisnove.serverServiceAccount" $ }}{{ else if eq $component "ui" }}{{ include "xisnove.uiServiceAccount" $ }}{{ else }}{{ include "xisnove.agentServiceAccount" $ }}{{ end }}
  labels:
    {{- include "xisnove.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
