database:
  profile: tursoManaged
  tursoManaged:
    existingSecret:
      name: xisnove-turso
server:
  replicas: 3
secrets:
  server:
    existingSecret:
      name: xisnove-server
  admin:
    email: admin@example.test
    existingSecret:
      name: xisnove-admin
  ui:
    existingSecret:
      name: xisnove-ui
